// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzlmctwgqanotxfxgipv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6bG1jdHdncWFub3R4ZnhnaXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjIwNTEsImV4cCI6MjA2MDYzODA1MX0.7J7bQ-zNWYiegAGXOgEyJ-9-wxO9Sx-4Jr7JC7uFfvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);